
import { ComplaintPost, GeneralPost } from '../interfaces/post.interface';

export const denuncias: ComplaintPost[] = [
  {
    _id: '1',
    postType: 'denuncia',
    title: 'Perro abandonado en la calle 5',
    content: 'Un perro de raza mestiza ha sido abandonado y se encuentra en mal estado.',
    user: 'user-1',
    categories: ['abandono', 'perros'],
    comments: [],
    createdAt: '2024-08-01T10:00:00Z',
    updatedAt: '2024-08-01T10:00:00Z',
    status: 'pendiente',
    location: 'Calle 5 y Av. Principal',
    evidence: ['https://example.com/evidence1.jpg'],
  },
  {
    _id: '2',
    postType: 'denuncia',
    title: 'Gato atrapado en un árbol',
    content: 'Hay un gato que no puede bajar de un árbol desde hace dos días.',
    user: 'user-2',
    categories: ['rescate', 'gatos'],
    comments: [],
    createdAt: '2024-08-02T12:30:00Z',
    updatedAt: '2024-08-02T12:30:00Z',
    status: 'publicado',
    location: 'Parque Central',
    evidence: [],
  },
  {
    _id: '3',
    postType: 'denuncia',
    title: 'Venta ilegal de animales exóticos',
    content: 'Se sospecha de venta ilegal de aves exóticas en un mercado local.',
    user: 'user-3',
    categories: ['tráfico ilegal', 'aves'],
    comments: [],
    createdAt: '2024-08-03T15:00:00Z',
    updatedAt: '2024-08-03T15:00:00Z',
    status: 'resuelto',
    location: 'Mercado de la Ciudad',
    evidence: ['https://example.com/evidence2.jpg', 'https://example.com/evidence3.jpg'],
  },
  {
    _id: '4',
    postType: 'denuncia',
    title: 'Caballo desnutrido',
    content: 'Un caballo utilizado para tirar de una carreta se ve extremadamente delgado.',
    user: 'user-4',
    categories: ['maltrato', 'caballos'],
    comments: [],
    createdAt: '2024-08-04T09:00:00Z',
    updatedAt: '2024-08-04T09:00:00Z',
    status: 'pendiente',
    location: 'Zona rural, km 10',
    evidence: [],
  },
  {
    _id: '5',
    postType: 'denuncia',
    title: 'Criadero ilegal de perros',
    content: 'Se escuchan ladridos constantes y los animales parecen estar en malas condiciones.',
    user: 'user-5',
    categories: ['criadero ilegal', 'perros'],
    comments: [],
    createdAt: '2024-08-05T11:20:00Z',
    updatedAt: '2024-08-05T11:20:00Z',
    status: 'publicado',
    location: 'Calle Falsa 123',
    evidence: ['https://example.com/evidence4.jpg'],
  },
  {
    _id: '6',
    postType: 'denuncia',
    title: 'Contaminación de río',
    content: 'Una fábrica está vertiendo desechos directamente en el río.',
    user: 'user-6',
    categories: ['contaminación', 'medio ambiente'],
    comments: [],
    createdAt: '2024-08-06T14:00:00Z',
    updatedAt: '2024-08-06T14:00:00Z',
    status: 'pendiente',
    location: 'Río Claro, cerca de la zona industrial',
    evidence: ['https://example.com/evidence5.mp4'],
  },
  {
    _id: '7',
    postType: 'denuncia',
    title: 'Tala ilegal de árboles',
    content: 'Se están talando árboles en una zona protegida durante la noche.',
    user: 'user-7',
    categories: ['deforestación', 'medio ambiente'],
    comments: [],
    createdAt: '2024-08-07T18:00:00Z',
    updatedAt: '2024-08-07T18:00:00Z',
    status: 'resuelto',
    location: 'Bosque La Esperanza',
    evidence: [],
  },
  {
    _id: '8',
    postType: 'denuncia',
    title: 'Caza furtiva de venados',
    content: 'Se han encontrado trampas para venados en el bosque.',
    user: 'user-8',
    categories: ['caza furtiva', 'fauna silvestre'],
    comments: [],
    createdAt: '2024-08-08T20:15:00Z',
    updatedAt: '2024-08-08T20:15:00Z',
    status: 'publicado',
    location: 'Reserva Natural El Silencio',
    evidence: ['https://example.com/evidence6.jpg'],
  },
  {
    _id: '9',
    postType: 'denuncia',
    title: 'Animales envenenados',
    content: 'Varios perros y gatos de la comunidad han aparecido muertos, se sospecha de envenenamiento.',
    user: 'user-9',
    categories: ['envenenamiento', 'perros', 'gatos'],
    comments: [],
    createdAt: '2024-08-09T08:45:00Z',
    updatedAt: '2024-08-09T08:45:00Z',
    status: 'pendiente',
    location: 'Barrio Las Flores',
    evidence: [],
  },
  {
    _id: '10',
    postType: 'denuncia',
    title: 'Peleas de gallos',
    content: 'Se organizan peleas de gallos todos los fines de semana en una finca.',
    user: 'user-10',
    categories: ['peleas de animales', 'aves'],
    comments: [],
    createdAt: '2024-08-10T22:00:00Z',
    updatedAt: '2024-08-10T22:00:00Z',
    status: 'rechazado',
    location: 'Finca "El Gallo Negro"',
    evidence: [],
  },
];

export const noticias: GeneralPost[] = [
  {
    _id: '11',
    postType: 'noticia',
    title: 'Campaña de esterilización gratuita',
    content: 'El próximo mes se realizará una campaña de esterilización para perros y gatos en el centro comunitario.',
    user: 'admin-1',
    categories: ['campañas', 'esterilización'],
    comments: [],
    createdAt: '2024-08-01T09:00:00Z',
    updatedAt: '2024-08-01T09:00:00Z',
  },
  {
    _id: '12',
    postType: 'noticia',
    title: 'Nueva ley de protección animal aprobada',
    content: 'El congreso ha aprobado una nueva ley que endurece las penas por maltrato animal.',
    user: 'admin-1',
    categories: ['legislación', 'protección animal'],
    comments: [],
    createdAt: '2024-08-02T11:00:00Z',
    updatedAt: '2024-08-02T11:00:00Z',
  },
  {
    _id: '13',
    postType: 'noticia',
    title: 'Rescate exitoso de delfines varados',
    content: 'Un grupo de voluntarios logró rescatar a tres delfines que habían quedado varados en la playa.',
    user: 'admin-2',
    categories: ['rescate', 'fauna marina'],
    comments: [],
    createdAt: '2024-08-03T14:30:00Z',
    updatedAt: '2024-08-03T14:30:00Z',
  },
  {
    _id: '14',
    postType: 'noticia',
    title: 'Jornada de adopción este fin de semana',
    content: 'No te pierdas la oportunidad de darle un hogar a un amigo peludo en nuestra jornada de adopción.',
    user: 'admin-1',
    categories: ['adopción', 'eventos'],
    comments: [],
    createdAt: '2024-08-04T16:00:00Z',
    updatedAt: '2024-08-04T16:00:00Z',
  },
  {
    _id: '15',
    postType: 'noticia',
    title: 'Aumento de la población de cóndores andinos',
    content: 'Gracias a los esfuerzos de conservación, la población de cóndores ha mostrado un notable aumento.',
    user: 'admin-2',
    categories: ['conservación', 'aves'],
    comments: [],
    createdAt: '2024-08-05T13:00:00Z',
    updatedAt: '2024-08-05T13:00:00Z',
  },
  {
    _id: '16',
    postType: 'noticia',
    title: 'Inauguración de nuevo refugio para animales',
    content: 'Se ha inaugurado un nuevo refugio con capacidad para 200 animales sin hogar.',
    user: 'admin-1',
    categories: ['refugios', 'infraestructura'],
    comments: [],
    createdAt: '2024-08-06T10:00:00Z',
    updatedAt: '2024-08-06T10:00:00Z',
  },
  {
    _id: '17',
    postType: 'noticia',
    title: 'Día mundial de los océanos: un llamado a la acción',
    content: 'En el día mundial de los océanos, expertos nos recuerdan la importancia de proteger nuestros mares.',
    user: 'admin-2',
    categories: ['medio ambiente', 'océanos'],
    comments: [],
    createdAt: '2024-08-07T09:30:00Z',
    updatedAt: '2024-08-07T09:30:00Z',
  },
  {
    _id: '18',
    postType: 'noticia',
    title: 'Voluntarios limpian 2 toneladas de basura de la playa',
    content: 'Un grupo de 50 voluntarios recolectó más de 2 toneladas de plástico y otros desechos de la playa principal.',
    user: 'admin-1',
    categories: ['voluntariado', 'limpieza', 'medio ambiente'],
    comments: [],
    createdAt: '2024-08-08T17:00:00Z',
    updatedAt: '2024-08-08T17:00:00Z',
  },
  {
    _id: '19',
    postType: 'noticia',
    title: 'Descubren nueva especie de rana en la Amazonía',
    content: 'Científicos han descubierto una nueva especie de rana de cristal en una remota área de la Amazonía.',
    user: 'admin-2',
    categories: ['descubrimientos', 'fauna silvestre'],
    comments: [],
    createdAt: '2024-08-09T11:45:00Z',
    updatedAt: '2024-08-09T11:45:00Z',
  },
  {
    _id: '20',
    postType: 'noticia',
    title: 'Taller sobre compostaje casero',
    content: 'Aprende a reducir tus desechos y a crear abono para tus plantas en nuestro taller gratuito de compostaje.',
    user: 'admin-1',
    categories: ['talleres', 'reciclaje', 'medio ambiente'],
    comments: [],
    createdAt: '2024-08-10T15:00:00Z',
    updatedAt: '2024-08-10T15:00:00Z',
  },
];

export const recomendaciones: GeneralPost[] = [
  {
    _id: '21',
    postType: 'recomendacion',
    title: 'Cómo cuidar a tu cachorro recién adoptado',
    content: 'Te damos los mejores consejos para que los primeros días de tu nuevo cachorro en casa sean perfectos.',
    user: 'vet-1',
    categories: ['cuidados', 'perros', 'adopción'],
    comments: [],
    createdAt: '2024-08-01T11:00:00Z',
    updatedAt: '2024-08-01T11:00:00Z',
  },
  {
    _id: '22',
    postType: 'recomendacion',
    title: 'La importancia de la vacunación en gatos',
    content: 'Descubre por qué es fundamental mantener al día el calendario de vacunación de tu gato.',
    user: 'vet-1',
    categories: ['salud', 'gatos', 'vacunación'],
    comments: [],
    createdAt: '2024-08-02T14:00:00Z',
    updatedAt: '2024-08-02T14:00:00Z',
  },
  {
    _id: '23',
    postType: 'recomendacion',
    title: 'Juguetes caseros para entretener a tu mascota',
    content: 'No necesitas gastar mucho dinero para mantener a tu mascota entretenida. ¡Te enseñamos a hacer juguetes en casa!',
    user: 'trainer-1',
    categories: ['enriquecimiento ambiental', 'juguetes', 'DIY'],
    comments: [],
    createdAt: '2024-08-03T16:30:00Z',
    updatedAt: '2024-08-03T16:30:00Z',
  },
  {
    _id: '24',
    postType: 'recomendacion',
    title: 'Alimentos tóxicos para perros que debes evitar',
    content: 'Conoce la lista de alimentos comunes en nuestros hogares que pueden ser peligrosos para tu perro.',
    user: 'vet-1',
    categories: ['nutrición', 'perros', 'seguridad'],
    comments: [],
    createdAt: '2024-08-04T18:00:00Z',
    updatedAt: '2024-08-04T18:00:00Z',
  },
  {
    _id: '25',
    postType: 'recomendacion',
    title: 'Cómo reducir tu huella de carbono en casa',
    content: 'Pequeños cambios en tu día a día pueden tener un gran impacto en el medio ambiente. Aquí te dejamos algunas ideas.',
    user: 'eco-expert-1',
    categories: ['sostenibilidad', 'medio ambiente', 'hogar'],
    comments: [],
    createdAt: '2024-08-05T15:00:00Z',
    updatedAt: '2024-08-05T15:00:00Z',
  },
  {
    _id: '26',
    postType: 'recomendacion',
    title: 'Beneficios de adoptar un animal adulto',
    content: 'Los animales adultos también merecen una oportunidad. Descubre las ventajas de adoptar una mascota mayor.',
    user: 'rescuer-1',
    categories: ['adopción', 'consejos'],
    comments: [],
    createdAt: '2024-08-06T12:00:00Z',
    updatedAt: '2024-08-06T12:00:00Z',
  },
  {
    _id: '27',
    postType: 'recomendacion',
    title: 'Identifica las señales de estrés en tu gato',
    content: 'Los gatos son expertos en ocultar su malestar. Aprende a identificar las señales de que tu gato está estresado.',
    user: 'vet-2',
    categories: ['comportamiento', 'gatos', 'salud'],
    comments: [],
    createdAt: '2024-08-07T13:45:00Z',
    updatedAt: '2024-08-07T13:45:00Z',
  },
  {
    _id: '28',
    postType: 'recomendacion',
    title: 'Cómo construir un refugio para aves en tu jardín',
    content: 'Atrae aves a tu jardín y ayúdalas a anidar construyendo un sencillo refugio con materiales reciclados.',
    user: 'eco-expert-1',
    categories: ['aves', 'jardinería', 'DIY'],
    comments: [],
    createdAt: '2024-08-08T19:00:00Z',
    updatedAt: '2024-08-08T19:00:00Z',
  },
  {
    _id: '29',
    postType: 'recomendacion',
    title: 'Primeros auxilios para mascotas: lo que todo dueño debe saber',
    content: 'Estar preparado puede marcar la diferencia en una emergencia. Aprende los conceptos básicos de primeros auxilios para tu mascota.',
    user: 'vet-1',
    categories: ['salud', 'emergencias', 'primeros auxilios'],
    comments: [],
    createdAt: '2024-08-09T14:00:00Z',
    updatedAt: '2024-08-09T14:00:00Z',
  },
  {
    _id: '30',
    postType: 'recomendacion',
    title: '10 plantas de interior seguras para tus mascotas',
    content: 'Decora tu casa sin preocupaciones. Te presentamos una lista de plantas de interior que no son tóxicas para perros y gatos.',
    user: 'plant-lover-1',
    categories: ['hogar', 'seguridad', 'plantas'],
    comments: [],
    createdAt: '2024-08-10T17:30:00Z',
    updatedAt: '2024-08-10T17:30:00Z',
  },
];
